spring:
  application:
    name: presentation
  zipkin:
    baseUrl: http://zipkin/
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8080

zuul:
  ribbon:
    listOfServers: zuul:8080


hystrix:
  command:
    PricingCall:
      execution:
       isolation:
         thread:
           timeoutInMilliseconds: 2000
  threadpool:
    SalesThreads:
      coreSize: 20
      maxQueueSize: 200
      queueSizeRejectionThreshold: 200
      
      
security:
  user:
    password: none
  ignored:
  - "bower_components/**"
  - "scripts.js"
  - "bower.json"
  oauth2:
    client:
      accessTokenUri: http://authserver-lambdaair.b9ad.pro-us-east-1.openshiftapps.com/oauth/token
      userAuthorizationUri: http://authserver-lambdaair.b9ad.pro-us-east-1.openshiftapps.com/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----