spec:
  replicas: 1
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: '200m'
              memory: '200Mi'
            limits:
              cpu: '400m'
              memory: '400Mi'
