spec:
  replicas: 1
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: '400m'
              memory: '400Mi'
            limits:
              cpu: '800m'
              memory: '800Mi'
